### ISSUE TITLE
Custom Types support ?

### ISSUE THREAD

**Issue by fgaule** [spring-projects/spring-data-jdbc-ext#10]
Is there a way of supporting CustomTypes as QueryDSL suggest in its [documentation](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s03.html)? 

> 2.3.20. Custom types
> Querydsl SQL provides the possibility to declare custom type mappings for ResultSet/Statement > > > interaction. The custom type mappings can be declared in com.mysema.query.sql.Configuration
> instances, which are supplied as constructor arguments to the actual queries:
> 
>  Configuration configuration = new Configuration(new H2Templates());
>  // overrides the mapping for Types.DATE
> configuration.register(new UtilDateType());  
> And for a table column
> 
> Configuration configuration = new Configuration(new H2Templates());
> // declares a maping for the gender column in the person table
> configuration.register("person", "gender",  new EnumByNameType<Gender>(Gender.class));
> To customize a numeric mapping you can use the registerNumeric method like this
> 
> configuration.registerNumeric(5,2,Float.class);
> This will map the Float type to the NUMERIC(5,2) type."

**Comment by trisberg** [comment]
We have deprecated the QueryDSL support. Going forward it is better to switch to using the Querydsl APIs directly. For integration with Spring resource management you can utilize the `com.querydsl.sql.spring.SpringConnectionProvider` and `com.querydsl.sql.spring.SpringExceptionTranslator`
  classes.
