### ISSUE TITLE
OneToManyResultSetExtractor cannot be reused unless you override "extractData".

### ISSUE THREAD

**Issue by DeCaMil** [spring-projects/spring-data-jdbc-ext#11]
`OneToManyResultSetExtractor` cannot be reused unless you override `extractData`.

On the first call to `extractData`, the `results` member is null and a new ArrayList is allocated. If the same instance of the extractor is reused in a subsequent query, it begins with `results` already holding the results of the prior query. Any new records returned by the query are now added to the existing results.

This is contrary to ResultSetExtractor Javadoc.
<blockquote>
... a ResultSetExtractor object is typically stateless and thus reusable, as long as it doesn't access stateful resources (such as output streams when streaming LOB contents) or keep result state within the object
</blockquote>

It should be reusable and `results.clear()` should be called to prevent returning previous results.

**Comment by trisberg** [comment]
Closed with https://github.com/spring-projects/spring-data-jdbc-ext/commit/e2af2e354e4e6cc3b79008e3aa412643d9668cbd
