### ISSUE TITLE
QueryDslJdbcTemplate NPE when using list method on newSqlQuery

### ISSUE THREAD

**Issue by aug828** [spring-projects/spring-data-jdbc-ext#14]
When I use something like this: 

```
template.newSqlQuery().from(q).list(q.name);
```

it throws NPE. 

In AbstractSQLQuery.java, the conn is null when using list method. 

```
final PreparedStatement stmt = conn.prepareStatement(queryString);
```

**Comment by aug828** [comment]
I think the fix should be: 
QueryDslJdbcTemplate.java method newSqlQuery should change from 
```
public SQLQuery newSqlQuery() {
   return new SQLQuery(this.dialect);
}
```

to 
```
public SQLQuery newSqlQuery() {
   Connection conn = DataSourceUtils.getConnection(this.jdbcTemplate.getDataSource());
   return new SQLQuery(conn,this.dialect);
}
```

**Comment by trisberg** [comment]
We have deprecated the QueryDSL support. Going forward it is better to switch to using the Querydsl APIs directly. For integration with Spring resource management you can utilize the `com.querydsl.sql.spring.SpringConnectionProvider` and `com.querydsl.sql.spring.SpringExceptionTranslator`
  classes.
