### ISSUE TITLE
Return values need to be documented better

### ISSUE THREAD

**Issue by utaboro** [spring-projects/spring-data-jdbc-ext#15]
Documentation of QueryDslJdbcOperations needs fixing on return values. For example
https://github.com/spring-projects/spring-data-jdbc-ext/blob/master/spring-data-jdbc-core/src/main/java/org/springframework/data/jdbc/query/QueryDslJdbcOperations.java#L113 needs fixing. @Return should be "the mapped object or null if no row was found" or similar.

Btw. returning null instead of throwing an exception is not in line with the implementation of JdbcTemplate.

**Comment by trisberg** [comment]
Thanks for reporting this - I've added a JIRA issue to track this - https://jira.spring.io/browse/DATAJDBC-72

**Comment by trisberg** [comment]
We have deprecated the QueryDSL support. Going forward it is better to switch to using the Querydsl APIs directly. For integration with Spring resource management you can utilize the `com.querydsl.sql.spring.SpringConnectionProvider` and `com.querydsl.sql.spring.SpringExceptionTranslator`
  classes.
