### ISSUE TITLE
is spring data jdbc support postgresql

### ISSUE THREAD

**Issue by arunnairmr** [spring-projects/spring-data-jdbc-ext#16]
hey, is spring data jdbc support postgresql database.

**Comment by trisberg** [comment]
Hi,

Yes, most of the JDBC support is in the core Spring Framework project and we do support PostgreSQL.

We also have a JDBC Extensions project with some additional support. There are two parts to the JDBC Extensions project. One part is specific to Oracle like Advanced Data Type support,  Fast Connection Failover etc. The other part is generic support for using Querydsl and a one-to-many RowMapper that can be useful, so this part could be useful for PostgreSQL.

**Comment by arunnairmr** [comment]
OK. I have already tried this.but when i give postgresql as type of jdbc:embedded-database , its give error.

<jdbc:embedded-database id="dataSource" type="POSTGRES">
		<jdbc:script location="classpath:core-db-init.sql"/>
</jdbc:embedded-database>

**Comment by trisberg** [comment]
PostgreSQL doesn't run as an embedded database, you would need to run it as a separate process. The databases that can run as embedded are HSQL, H2 and Derby.

**Comment by artembilan** [comment]
That's correct.
There is no such an embedded library for PostgreSQL.
Valid RDBMS are:
> The type of embedded database to create, such as HSQL, H2 or Derby. Defaults to HSQL.

From the description of that `type` attribute.

Hence you are forced to use the real external PostgreSQL server.
Consider to configure:
````xml
<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource"
		destroy-method="close">
		<property name="driverClassName" value="org.postgresql.Driver" />
		<property name="initialSize" value="10"/>
		<property name="url"
			value="jdbc:postgresql:integration" />
		<property name="username" value="postgres" />
		<property name="password" value="postgres" />
</bean>
````

**Comment by arunnairmr** [comment]
can you please show me a sample java code for a insert function into postgresql.

**Comment by trisberg** [comment]
You would be better off posting this last question on StackOverflow with a spring-jdbc tag. That way you would get a lot more people to look at it and provide some help.
