### ISSUE TITLE
Connection preparer is not  working (over) the Proxy connection

### ISSUE THREAD

**Issue by ftanil** [spring-projects/spring-data-jdbc-ext#17]
"Custom DataSource Connection Preparer" doesn't work with the "Configuration of a Proxy Authentication", when oracle connection is set to a proxy connection all the session level information set by connection preparer is lost. 
There should a way that connection preparer is invoked after (over) the Proxy connection, not before.

**Comment by trisberg** [comment]
Hi, I created a JIRA issue to track this - https://jira.spring.io/browse/DATAJDBC-74

**Comment by davidkarlsen** [comment]
Maybe use a NativeJdbcExtractor to drill down to the underlying connection? I guess that's what's really wanted in most cases?
