### ISSUE TITLE
support for 3.x version of querydsl

### ISSUE THREAD

**Issue by vbichov** [spring-projects/spring-data-jdbc-ext#2]
Hi,

There are a few changes in querydsl (I found 1: https://github.com/mysema/querydsl/issues/186) that reqire changes in the spring-data-jdbc-ext  package.

The above change causes QueryDslJdbcTemplate.newSqlQuery() to throw ClassNotFoundException.

Are those changes planed in the near future?

Thank you,
Vitaly

**Comment by trisberg** [comment]
We have deprecated the QueryDSL support. Going forward it is better to switch to using the Querydsl APIs directly. For integration with Spring resource management you can utilize the `com.querydsl.sql.spring.SpringConnectionProvider` and `com.querydsl.sql.spring.SpringExceptionTranslator`
  classes.
