### ISSUE TITLE
Avoid deprecated Oracle types

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-data-jdbc-ext#20]
See 
https://docs.oracle.com/database/121/JAJDB/oracle/sql/STRUCT.html
"Deprecated. Use java.sql.Struct interface for declaration instead of using concrete class oracle.sql.STRUCT."

https://docs.oracle.com/database/121/JAJDB/oracle/sql/ARRAY.html
"Deprecated. Use java.sql.Array interface for declaration instead of using concrete class oracle.sql.ARRAY."

**Comment by trisberg** [comment]
Yes, this is something we are addressing i the 2.0.x branch and tracking here - https://jira.spring.io/browse/DATAJDBC-78

**Comment by davidkarlsen** [comment]
When is 2.x due for release (There's no estimated release date on the milestone)

**Comment by trisberg** [comment]
I put some tentative dates on the releases, so September for 2.0 M1 and then GA by October.

**Comment by davidkarlsen** [comment]
Are we getting any closer?

**Comment by trisberg** [comment]
I'll try to get to this next couple of days

**Comment by davidkarlsen** [comment]
@trisberg How did it go? Can't find anything in central?

**Comment by trisberg** [comment]
I just released 2.0.0.M1, it's in the Spring Milestone Repo (http://repo.spring.io/milestone)

**Comment by davidkarlsen** [comment]
Maybe time to get an GA out the door (and not a milestone)?
