### ISSUE TITLE
Support for 4.x querydsl

### ISSUE THREAD

**Issue by cudek** [spring-projects/spring-data-jdbc-ext#21]
Hi!
Could you, please, add a support for querydsl 4.x? In the new version of that framework all packaging structure has been changed, therefore it is not possible to use jdbc-extensions with a 4.x version of querydsl.

Warm Regards,
Tomasz Cudek

**Comment by trisberg** [comment]
Hi,

Yes, this is something we will have to do although it will break existing apps. Created a JIRA issue for it - https://jira.spring.io/browse/DATAJDBC-79

-Thomas

**Comment by trisberg** [comment]
We have deprecated the QueryDSL support. Going forward it is better to switch to using the Querydsl APIs directly. For integration with Spring resource management you can utilize the `com.querydsl.sql.spring.SpringConnectionProvider` and `com.querydsl.sql.spring.SpringExceptionTranslator`
  classes.
