### ISSUE TITLE
Add support for ResultTransformer to QueryDslJdbcTemplate

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-data-jdbc-ext#23]
If you add a method like below, this will allow transforming result.

```
  public <V> V query(final SQLQuery sqlQuery, final ResultTransformer<V> transformer) {
    V results = jdbcTemplate.execute(new ConnectionCallback<V>() {
        public V doInConnection(Connection con) throws SQLException,
                DataAccessException {
            SQLQuery liveQuery = sqlQuery.clone(con);
            try {
                return liveQuery.transform(transformer);
            } catch (QueryException qe) {
                throw translateQueryException(qe, "SQLQuery", liveQuery.toString());
            }
        }});
    return results;
}
```

example use case

```
    QFxmatchProfiles qProfiles = QFxmatchProfiles.fxmatchProfiles;
    SQLQuery query = queryDslJdbcTemplate.newSqlQuery()
            .from(qProfiles)
            .where(qProfiles.profile.eq(profile));
    return queryDslJdbcTemplate.query(query, GroupBy.groupBy(qProfiles.menu).as(qProfiles));
```

This will return `Map<String, FxmatchProfiles>`, key as menu and value as item.

**Comment by trisberg** [comment]
Added JIRA issue - https://jira.spring.io/browse/DATAJDBC-81

**Comment by gokhanoner** [comment]
also, if JDBCTemplate parameter can be protected instead of private, I can simply extend the ```QueryDslJdbcTemplate``` and use it. Now, as a workaround, I copied all the code to a new class & changed add ```QueryDslJdbcTemplate``` to my new class..

**Comment by trisberg** [comment]
With the changing APIs and the package change to `com.querydsl` it doesn't seem workable to maintain the QueryDslJdbcTemplate. I think it would be better to switch to using the Querydsl APIs directly. For integration with Spring resource management you can
  utilize the `com.querydsl.sql.spring.SpringConnectionProvider` and `com.querydsl.sql.spring.SpringExceptionTranslator`
  classes. Does that seem workable?
