### ISSUE TITLE
OracleXmlHandler.getXmlAsString throws NPE instead of returning null

### ISSUE THREAD

**Issue by gigermocas** [spring-projects/spring-data-jdbc-ext#24]
According to the documentation for SqlXmlHandler's getXmlAsString it should return the given column as String or null in case of SQL NULL, OracleXmlHandler's implementation throws a NullPointerException instead.

The default implementation (Jdbc4SqlXmlHandler) has the same behavior. So it seems to me that there's a discrepancy between the documentation and the implementation.

**Comment by jhoeller** [comment]
FYI, I intend to fix this in `Jdbc4SqlXmlHandler` in 4.2.4 / 4.1.9 / 3.2.16 next week: https://jira.spring.io/browse/SPR-13782
