### ISSUE TITLE
Hope spring-data-jdbc-ext support mysql and mariadb

### ISSUE THREAD

**Issue by zhengfc** [spring-projects/spring-data-jdbc-ext#26]
Hope spring-data-jdbc-ext isolate the different relation db, refine the new branch spring-data-jdbc-mysql, not just oracle

**Comment by trisberg** [comment]
The main JDBC support is provided by the `spring-jdbc` sub-project of the core Spring Framework project (https://github.com/spring-projects/spring-framework). This extensions project provide database specific extensions. Anything MySQL specific you'd like to see?
