### ISSUE TITLE
Spring Framework 5.0 Support?

### ISSUE THREAD

**Issue by Fydon** [spring-projects/spring-data-jdbc-ext#27]
Is this being dropped or is Spring Framework 5.0 support planned?

I noticed that the Contributing section has a link to a forum and JIRA that doesn't work.

**Comment by trisberg** [comment]
This project is focusing on providing support for Oracle specific features and we have no specific plans for Spring 5.0 support as of yet. Thanks for pointing out the JIRA link, we are switching this project to use GitHub issues going forward.
