### ISSUE TITLE
Update Spring version

### ISSUE THREAD

**Issue by trisberg** [spring-projects/spring-data-jdbc-ext#29]
At the moment Spring Data JDBC still uses Spring 3.0. Would be nice if it would be build against a still supported version preferably on the 4.x range but at least the 3.2.x range.

**Comment by soudmaijer** [comment]
How about Spring 5? In Spring 5 the jdbc.support.nativejdbc is removed. Maybe consider adding this to the spring-data-jdbc-ext.

**Comment by sLite** [comment]
Is there any near/mid term plan to support Spring 5 & Spring Data 2?
We are using `AqJmsFactoryBeanFactory` with `setCoordinateWithDataSourceTransactions(true)` and are planning our Spring 5 migration.

Regarding the removal of `jdbc.support.nativejdbc` this sounds like a more involving task... Any thoughts on that?

**Comment by hakamairi** [comment]
I would really love to see this move forward. Submitted a PR about this.
Had a really hard time with running the `spring-data-oracle-test`, I'm a docker guy and it wasn't nice (the whole sample data dependency and others).

Anyway I could support you more on this, just let me know what's needed.

**Comment by schauder** [comment]
We had an internal discussion about this project and decided to move it to the attic.
So we won't resolve this issue nor any of the other.

I'll just have to find a slice of time to make this official.

**Comment by nc-jfkh** [comment]
Any news on this? We're relying on this project, but it disallows us upgrading to spring boot 5. 

Is there any alternative, or should we rewrite it ourselves sin NativeJdbcExtractorAdapter?

**Comment by nc-jfkh** [comment]
@soudmaijer Is your repo public - or could you make it?

**Comment by cmoro-deusto** [comment]
@schauder so the functionality provided by this lib is gonna be covered by the main spring data jdbc project or just being abandoned? In enterprise environments using Oracle is quite common to find advanced data types, currently only available in spring-data-jdbc-ext. Would you please clarify? Thanks a lot!

**Comment by schauder** [comment]
There is currently no plan to incorporate features from spring-data-jdbc-ext into spring-data-jdbc.

**Comment by isae** [comment]
Sorry for necroposting, I've encountered the issue only now.

According to https://docs.oracle.com/database/121/ADQUE/aq_envir.htm#ADQUE0300:
> Java package oracle.AQ was deprecated in 10g Release 1 (10.1). Oracle recommends that you migrate existing Java AQ applications to Oracle JMS (or other Java APIs) and use Oracle JMS (or other Java APIs) to design your future Java AQ applications.

Thus it is not sufficient to support these dependencies. The project, if it is needed, must depend on Oracle's _aqapi_ library instead:
```xml
<dependency>
  <groupId>com.oracle.aq</groupId>
  <artifactId>aqapi</artifactId>
  <version>11.2.0.3</version>
</dependency>
```

Otherwise, one could define Oracle's connection factory as a Spring bean:
```xml
<bean id="connectionFactory" class="oracle.jms.AQjmsConnectionFactory" 
                                    p:datasource-ref="jmsDataSource"
/>
``` 
instead of 
```xml
<bean id="oracleSyncNativeJdbcExtractor" class="org.springframework.jdbc.support.nativejdbc.SimpleNativeJdbcExtractor"/>

<orcl:aq-jms-connection-factory id="connectionFactory"
                                    data-source="jmsDataSource"
                                    use-local-data-source-transaction="true"
                                    native-jdbc-extractor="oracleSyncNativeJdbcExtractor"
 />
```

Maybe it is worth mentioning on main page of the project, because this information is kinda hard to google.
