### ISSUE TITLE
Unable to perform durable topic subscription via AdtMessageListenerContainer

### ISSUE THREAD

**Issue by kromg** [spring-projects/spring-data-jdbc-ext#31]
Hi, 
   I was trying to get a durable topic subscription using AdtMessageListenerContainer, but apparently it ignores setSubscriptionDurable() and setPubSubDomain() completely. This was my attempt: 

 	@Bean
	public AdtMessageListenerContainer jmsListenerContainer() throws JMSException {
	
		AdtMessageListenerContainer c =
			new AdtMessageListenerContainer();
	
		c.setSubscriptionDurable(true);
		c.setPubSubDomain(true);
		c.setSubscriptionShared(false);
		c.setClientId("CLIENT_ID");
		c.setDurableSubscriptionName("SUB_NAME");
		c.setDestinationName("TOPIC_NAME");
		c.setSessionTransacted(false);
		c.setTransactionManager(null);
		c.setMessageListener(new MyAQMessageListener());
	
		// The connection factory
		Properties info = new Properties();
		info.put("driver-name", "oracle.jdbc.OracleDriver");
		info.put("user", "user");
		info.put("password", "password");
		c.setConnectionFactory(
			oracle.jms.AQjmsFactory.getTopicConnectionFactory("jdbc:oracle:thin:@DB_NAME", info)
		);
	
		return c;
	}

No matter what I try, the subscription is always named TSUB_1_* (with a variable id), and not "SUB_NAME". 
Apparently, I fixed this by providing an alternative implementation which uses a createConsumer() method resembling that of AbstractMessageListenerContainer:

	public class AQMessageListenerContainer extends DefaultMessageListenerContainer {

		@Override
		protected MessageConsumer createConsumer(Session session, Destination destination) throws JMSException {
			if (isPubSubDomain() && destination instanceof Topic) {
				if (isSubscriptionDurable()) {
					return ((AQjmsSession) session).createDurableSubscriber(
							(Topic) destination,
							getSubscriptionName(),
							getMessageSelector(),
							isPubSubNoLocal(),
							new OraDataFactory()
					);
				} else {
					return ((AQjmsSession) session).createSubscriber((Topic) destination);
				}
			} else {
				return ((AQjmsSession) session).createConsumer(
						destination,
						getMessageSelector(),
						new OraDataFactory(),
						null,
						isPubSubNoLocal());
			}
		}
	
		protected void doShutdown() throws JMSException {
			super.doShutdown();
			logger.info("Shut down complete.");
		}
	}

Am I missing something or is AdtMessageListenerContainer really ignoring topic/subscription properties?

**Comment by olivergierke** [comment]
Sure you've filed against the right project? Looks like you were rather looking for something JMS?

**Comment by kromg** [comment]
The class I'm talking about is org.springframework.data.jdbc.jms.listener.oracle.AdtMessageListenerContainer, I found it under: spring-data-jdbc-ext/spring-data-oracle/src/main/java/org/springframework/data/jdbc/jms/listener/oracle/

I thought this was the right place (if it isn't, I apologize).

**Comment by olivergierke** [comment]
Oh, okay. Paging @trisberg then :)
