### ISSUE TITLE
Misspelled XML Namespace Declarations

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-data-jdbc-ext#37]
It appears there are a few misspelled declarations in the test file `test-orcl-interceptor.xml`:

* https://github.com/spring-projects/spring-data-jdbc-ext/blob/9f19335f6f776ad36158cfaa0f5aad64333ce988/spring-data-oracle/src/test/resources/org/springframework/data/jdbc/aop/test-orcl-interceptor.xml#L6
* https://github.com/spring-projects/spring-data-jdbc-ext/blob/9f19335f6f776ad36158cfaa0f5aad64333ce988/spring-data-oracle/src/test/resources/org/springframework/data/jdbc/aop/test-orcl-interceptor.xml#L14

**Comment by rwinch** [comment]
@schauder Is there a reason this got closed? The misspellings are still present in the examples I provided:


https://github.com/spring-projects/spring-data-jdbc-ext/blob/ff2709b2ba3029a5c36f91e1748065f10646a999/spring-data-oracle/src/test/resources/org/springframework/data/jdbc/aop/test-orcl-interceptor.xml#L6

```diff
<       xmlns:data-sql="http://www.springframnework.org/schema/data-sql"
>       xmlns:data-sql="http://www.springframework.org/schema/data-sql"
```


https://github.com/spring-projects/spring-data-jdbc-ext/blob/master/spring-data-oracle/src/test/resources/org/springframework/data/jdbc/aop/test-orcl-interceptor.xml#L13-L14

```diff
<       https://www.springframewok/schema/data-sql/spring-data-sql-1.0.xsd
>       https://www.springframework/schema/data-sql/spring-data-sql-1.0.xsd"
```

**Comment by schauder** [comment]
This project is no longer maintained for quite some time now and I just went around and closed all open tickets and PRs.
