### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-data-jdbc-ext#44]
The project won't build. I think the version of Gradle is so old that it is no longer available. It is on version 1.10, while 6.3 is the current version.

Here's the error (minus the stack trace):

Downloading http://services.gradle.org/distributions/gradle-1.10-bin.zip

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-1.10-bin.zip

**Comment by schauder** [comment]
@Buzzardo Sorry for the confusion. As the Readme says:

>NOTICE: This project has been archived as of March 27th, 2019. There will be no maintenance or new development going forward.
